#when building docker image
#select cd current_file_path in terminal
#run in terminal docker-compose up --build
#then run streamlit and fastapi http://localhost:8501/,http://localhost:8000/

version: "3.9"

services:

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    ports:
      - "8000:8000"

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    depends_on:
      - fastapi


# #now directly use from docker hub avoid to build 
# services:

#   fastapi:
#     image: chetansgode/project-1-demand_forecasting-fastapi
#     ports:
#       - "8000:8000"

#   streamlit:
#     image: chetansgode/project-1-demand-forecasting-streamlit:latest
#     ports:
#       - "8501:8501"
#     depends_on:
#       - fastapi